// {
//   Avalanche    : '/Future/Avalanche.htm',
//   Blackhawks   : '/Future/Blackhawks.htm',
//   Blue Jackets : '/Future/BlueJackets.htm',
//   Blues        : '/Future/Blues.htm',
//   Bruins       : '/Future/Bruins.htm',
//   Canadiens    : '/Future/Canadiens.htm',
//   Canucks      : '/Future/Canucks.htm',
//   Capitals     : '/Future/Capitals.htm',
//   Coyotes      : '/Future/Coyotes.htm',
//   Devils       : '/Future/Devils.htm',
//   Ducks        : '/Future/Ducks.htm',
//   Flames       : '/Future/Flames.htm',
//   Flyers       : '/Future/Flyers.htm',
//   Hurricanes   : '/Future/Hurricanes.htm',
//   Islanders    : '/Future/Islanders.htm',
//   Jets         : '/Future/Jets.htm',
//   Kings        : '/Future/Kings.htm',
//   Lightning    : '/Future/Lightning.htm',
//   Maple Leafs  : '/Future/MapleLeafs.htm',
//   Oilers       : '/Future/Oilers.htm',
//   Panthers     : '/Future/Panthers.htm',
//   Penguins     : '/Future/Penguins.htm',
//   Predators    : '/Future/Predators.htm',
//   Rangers      : '/Future/Rangers.htm',
//   Red Wings    : '/Future/RedWings.htm',
//   Sabres       : '/Future/Sabres.htm',
//   Senators     : '/Future/Senators.htm',
//   Sharks       : '/Future/Sharks.htm',
//   Stars        : '/Future/Stars.htm',
//   Wild         : '/Future/Wild.htm'
// }
